#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat May 23 08:45:11 -04 2026
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view /home/abarf/Documents/repos/DASD4186132/assignment02/project_1/tb_top_behav.wcfg -view /home/abarf/Documents/repos/DASD4186132/assignment02/project_1/tb_top_post-impl.wcfg -view /home/abarf/Documents/repos/DASD4186132/assignment02/project_1/tb_top_post-synth.wcfg -log simulate.log"
xsim tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view /home/abarf/Documents/repos/DASD4186132/assignment02/project_1/tb_top_behav.wcfg -view /home/abarf/Documents/repos/DASD4186132/assignment02/project_1/tb_top_post-impl.wcfg -view /home/abarf/Documents/repos/DASD4186132/assignment02/project_1/tb_top_post-synth.wcfg -log simulate.log

